#! /bin/bash

function update_ps1() {
    MODULES="nix-shell,venv,user,ssh,cwd,perms,git,hg,jobs,exit"
    ARGUMENTS="-cwd-max-depth 3"
    PS1="$($GOPATH/bin/powerline-go -modules $MODULES $ARGUMENTS $?)"
}

if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="update_ps1; $PROMPT_COMMAND"
fi
